### ISSUE TITLE
Migracija na HTTPS zaradi boljše SEO vidljivosti

### ISSUE THREAD

**Issue by bostjan** [aokranj/website#14]
Ni bogvekaj, naj pa kak procent doda.

Bojč, reassignej ko boš vse uredil na devu.

b.

**Comment by bostjan** [comment]
Aja, https je tule že done, samo še ni urejen redirect:
https://www.aokranj.com/

b.

**Comment by HriBB** [comment]
Zgleda kul. Še kej rabiš od mene? Drugač pa kr obrni na https ;)

**Comment by HriBB** [comment]
Aha ne ... štekam. Bom preveril ko bom mel mal več motivacije :)

**Comment by bostjan** [comment]
Tole je urejeno.

Edini problem ki je še je z nekimi slikami, nimam zdele več energije.

**Comment by HriBB** [comment]
Bom preveril popoldne oziroma zvecer. Bos kej na stenci? :)

**Comment by bostjan** [comment]
Jp, 20:00
