### ISSUE TITLE
Refactoring: all configuration to conf/ or config/ directory

### ISSUE THREAD

**Issue by bostjan** [aokranj/website#24]
Tole je že zabava:
- public/config.inc.php
- public/wp-content/plugins/aokranj/config.php

Kaj če bi uredili tako, da se vsi config fajli hranijo v top level config/ direktoriju?
- config/wp-config.inc.php
- config/wp-plugin-aokranj.inc.php

Potem pa public/wp-config.inc.php kar commitamo, takega da ima defaulte ter vključi ../config/wp-config.inc.php.

Thoughts?

**Comment by bostjan** [comment]
Tole je urejeno.

Če ti manjka, uredi v config/... diru.

**Comment by HriBB** [comment]
Kul. Afro je bio pridan :)
