### ISSUE TITLE
%www.aokranj% string v bazi - a bi blo možno te URLje na relativno obliko spravit

### ISSUE THREAD

**Issue by bostjan** [aokranj/website#25]
Tega je:
* 3 v options tabeli (pričakovano)
* 2.5k v postmeta
* 25k v posts

A je možno, da se ```http://www.aokranj.com/wp-content/uploads/...``` spremeni tako, da se pusti samo ```/wp-contet/uploads/...``` ter da so url-ji relativni?

**Comment by HriBB** [comment]
Stupid wordpress ... bom preveril ;)

**Comment by bostjan** [comment]
Tole je malce irelevantno, oz. vsaj za tistih 22k vnosov, ki so GUIDi (zbrejka RSS če to spreminjaš, tudi če spremeniš URL).

**Comment by bostjan** [comment]
Dodatno: v config se lahko doda WP_HOME in WP_SITEURL, ki overrida kar je v bazi.

Problemi teh URLjev so pomojem predvsem v post contentih, kjer so fiksni.

**Comment by HriBB** [comment]
http://wordpress.stackexchange.com/questions/11993/wordpress-hook-before-inserting-post-into-database

Lahko bi rocno prekucal ves content preden gre v bazo?

**Comment by HriBB** [comment]
Hmm ... pomoje tole ne bo slo tok na izi http://stackoverflow.com/questions/17187437/relative-urls-in-wordpress

**Comment by bostjan** [comment]
Pust, sem z redirecti zrihtal. Navadno poganjanje gre preko HTTPSja, če je pa v postu link na HTTP, se pa redirecta na https pa je.

**Comment by HriBB** [comment]
Prima kt se rima!
