### ISSUE TITLE
Dodajanje utrinkov --> Dodaj Alpinistični smuk; Turni smuk pod kategorijo Utrinki

### ISSUE THREAD

**Issue by mzupin** [aokranj/website#29]
Kategorija Turni smuk in Alp. smuk, bi morala biti podkategorija, kategorije UTRINKOV.

**Comment by bostjan** [comment]
Huh, sej sta? Vsaka ima cca 500 pripadajočih utrinkov. Ali misliš da bi to morala bit ena kategorija z imenom "Alp. smuk, Turni smuk"?

b.
