### ISSUE TITLE
Naslovi ''ODSEK'' niso usklajeni

### ISSUE THREAD

**Issue by mzupin** [aokranj/website#37]
Bi bilo fajn, če bi bili tudi na desni zapisani vsi podnaslovi. 
Jaz sem iskal npr. pomembnejši vzponi in je bilo težko najt zgolj pod naslovi, ki se odprejo.

![slika](https://cloud.githubusercontent.com/assets/18151836/15446650/9efef426-1f27-11e6-85dd-bcbaa24457aa.png)

**Comment by bostjan** [comment]
@mzupin a je tole še odprto?

**Comment by mzupin** [comment]
Nope .. je ok se lahko zapre ...

*drugačen razpored je zaradi abecednega reda, po katerem wordpress sam
razvrsti naslove ...

2018-04-02 4:02 GMT+02:00 Boštjan Škufca <notifications@github.com>:

**Comment by mzupin** [comment]
Leave a comment
