### ISSUE TITLE
Create (not Vagrant but) Docker-based development environment

### ISSUE THREAD

**Issue by HriBB** [aokranj/website#7]
Fino bi blo naredit vagrant setup za development. Noter bi importal tudi dummy bazo in slike.

Kdor bi želel karkoli popravit, bi preprosto kloniral repo, pognal `vagrant up` in že bi imel working development environment.
- [ ] mysql dump
- [ ] export zadnjih 33 post slik
- [ ] export zadnje reportaže

**Comment by bostjan** [comment]
A bi bilo smotrno dumpat + importat produkcijsko bazo za to?

**Comment by HriBB** [comment]
Itak. Ampak je problem s slikami, ker jih je čist preveč in če želiš met kokr tok normalen working env rabis poste in slike, da vidis stajle ... mogoce bi se dalo naredit kak redirect ali kej podobnega, da bi slike ki ne obstajajo loadali direktno iz aokranj.com. Pa je spet problem ce delas offline ...

Bom se malo razmislu, sej tole se itak ne mudi ...

**Comment by bostjan** [comment]
Ja lahko se importa recimo zadnjih 10 postov, v celoti, a bi blo to za delo dovolj?

**Comment by HriBB** [comment]
Rajš recimo 33, da bomo lahko testirali še paging in podobne stvari.

**Comment by bostjan** [comment]
Tole je done, manjka le se #48.
